# Generated by Django 6.0.6 on 2026-06-29 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_element_aspect_cost_elementcomponent_element_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='components',
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='elements.element')),
            ],
            options={
                'ordering': ['result__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='elements.element')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='elements.recipe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipe', 'element'), name='unique_component_in_recipe')],
            },
        ),
    ]
