# Generated by Django 6.0.6 on 2026-06-29 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_remove_element_components_recipe_recipecomponent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='elementcomponent',
            name='unique_element_component_pair',
        ),
        migrations.DeleteModel(
            name='ElementComponent',
        ),
    ]
