# Generated by Django 5.2.4 on 2026-06-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_remove_elementcomponent_unique_element_component_pair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='aspect',
            field=models.CharField(choices=[('spark', 'SPARK'), ('snow', 'SNOW'), ('crystal', 'CRYSTAL'), ('bloom', 'BLOOM'), ('moon', 'MOON')], default='spark', max_length=24),
        ),
    ]
