# Generated by Django 5.2.4 on 2026-06-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_alter_element_aspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='aspect',
            field=models.CharField(choices=[('spark', 'SPARK'), ('snow', 'SNOW'), ('crystal', 'CRYSTAL'), ('bloom', 'BLOOM'), ('moon', 'MOON'), ('neutral', 'NEUTRAL')], default='spark', max_length=24),
        ),
    ]
